currency_rate_provider:
    calculate_rate_precision: 32
    display_rate_precision: 8
    cbr_provider:
        api_url: 'https://cbr.ru/scripts/XML_daily.asp'
        timeout: 30
        base_currency: RUB
        monitored_currencies:
            - USD
            - EUR
            - GBP
            - CNY

when@test:
    currency_rate_provider:
        cbr_provider:
            timeout: 5
            monitored_currencies:
                - USD
                - EUR

when@dev:
    currency_rate_provider:
        cbr_provider:
            timeout: 60
            monitored_currencies:
                - EUR
                - IRR
                - USD

