monolog:
    channels:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!currency_rate_bundle"]

        # Console handler - for development environment
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: error
                VERBOSITY_VERY_VERBOSE: debug
            channels: ["!currency_rate_bundle"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!currency_rate_bundle"]
when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                max_files: 10
                formatter: monolog.formatter.json
