monolog:
    channels:
        - currency_rates
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!currency_rates", "!currency_rate_provider"]

        currency_rates:
            type: stream
            path: "%kernel.logs_dir%/currency_rates.log"
            level: debug
            channels: [currency_rates]

        # Console handler - for development environment
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: error
                VERBOSITY_VERY_VERBOSE: debug
            channels: ["!currency_rate_provider", "!currency_rates"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!currency_rates", "!currency_rate_provider"]
when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                max_files: 10
                formatter: monolog.formatter.json
