twig:
    file_name_pattern: '*.twig'
#    form_themes:
#        - '@SonataAdmin/Form/filter_admin_fields.html.twig'
#        - '@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig'

when@test:
    twig:
        strict_variables: true

when@dev:
    twig:
        cache: false
        strict_variables: true
