<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260225130105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE current_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_currency CHAR(3) NOT NULL, target_currency CHAR(3) NOT NULL, value VARCHAR(255) NOT NULL, date DATE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_updated_at ON current_rate (updated_at)');
        $this->addSql('CREATE UNIQUE INDEX idx_base_target_currency ON current_rate (base_currency, target_currency)');
        $this->addSql('CREATE TABLE rate_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_currency CHAR(3) NOT NULL, target_currency CHAR(3) NOT NULL, value VARCHAR(255) NOT NULL, date DATE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_base_currency_date ON rate_history (base_currency, date)');
        $this->addSql('CREATE INDEX idx_target_currency_date ON rate_history (target_currency, date)');
        $this->addSql('CREATE INDEX idx_date ON rate_history (date)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE current_rate');
        $this->addSql('DROP TABLE rate_history');
    }
}
