# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# App controllers routes
_app_controllers:
    resource: ../src/Controller
    type: attribute

# Bundle controllers routes
_bundle_controllers:
    resource: ../src/Bundle
    type: attribute
