monolog:
    channels:
        - currency_rate_provider
    handlers:
        currency_rate_provider:
            type: stream
            path: "%kernel.logs_dir%/currency_rate_provider.log"
            level: debug
            channels: [currency_rate_provider]

when@dev:
    monolog:
        handlers:
            currency_rate_provider:
                type: stream
                path: "%kernel.logs_dir%/currency_rate_provider.log"
                level: debug
                channels: [currency_rate_provider]

when@prod:
    monolog:
        handlers:
            currency_rate_provider:
                type: stream
                path: "%kernel.logs_dir%/currency_rate_provider.log"
                level: info
                channels: [currency_rate_provider]

when@test:
    monolog:
        handlers:
            currency_rate_provider:
                type: stream
                path: "%kernel.logs_dir%/currency_rate_provider.log"
                level: debug
                channels: [currency_rate_provider]

