<?php

declare(strict_types=1);

namespace App\Bundle\CurrencyRateBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260309211848 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE current_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_currency CHAR NOT NULL, target_currency CHAR NOT NULL, value VARCHAR(255) NOT NULL, date DATE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_current_rate_date ON current_rate (date)');
        $this->addSql('CREATE INDEX idx_current_rate_date_base_target ON current_rate (date, base_currency, target_currency)');
        $this->addSql('CREATE UNIQUE INDEX idx_base_target_currency ON current_rate (base_currency, target_currency)');
        $this->addSql('CREATE TABLE rate_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_currency CHAR NOT NULL, target_currency CHAR NOT NULL, value VARCHAR(255) NOT NULL, date DATE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_rate_history_base_target_date ON rate_history (base_currency, target_currency, date)');
        $this->addSql('CREATE INDEX idx_rate_history_date ON rate_history (date)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE current_rate');
        $this->addSql('DROP TABLE rate_history');
    }
}
